site_name: Supernova
site_url: 'http://docs.supernovaegine.org'

pages:
- Home: 'index.md'
- Getting started:
  - Creating a basic project: 'getting-started/creating-a-basic-project.md'
  - Screen scaling: 'getting-started/screen-scaling.md'
- Building:
  - Building for Android: 'building/building-for-android.md'
  - Building for iOS: 'building/building-for-ios.md'
  - Building for HTML5: 'building/building-for-html5.md'

theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'

repo_name: 'deslon/supernova'
repo_url: 'https://github.com/deslon/supernova'
edit_uri: '../supernova-docs/edit/master/docs'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/deslon/supernova'

copyright: 'Copyright &copy; 2018, Eduardo Dória Lima (CC-BY 3.0)'

markdown_extensions:
  - admonition
  - codehilite
