site_name: Supernova
site_url: 'http://docs.supernovaegine.org'
site_author: 'Eduardo Dória Lima'
site_description: 'Supernova Engine documentation'

repo_name: 'deslon/supernova'
repo_url: 'https://github.com/deslon/supernova'
edit_uri: '../supernova-docs/edit/master/docs'

theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  #palette:
  #  primary: 'indigo'
  #  accent: 'indigo'
  feature:
    tabs: false

extra_css:
  - 'css/extra.css'
  - 'css/code-tabs.css'

extra_javascript:
  - 'js/code-tabs.js'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/deslon/supernova'
  version: 1.0

copyright: 'Copyright &copy; 2018, Eduardo Dória Lima (CC-BY 3.0)'

markdown_extensions:
  - admonition
  - codehilite
#      linenums: True
  - toc:
      permalink: true
  - markdown_fenced_code_tabs:
      single_block_as_tab: True

pages:
- Introduction: 'index.md'
- Learning:
  - Creating a basic project: 'learning/creating-a-basic-project.md'
  - Screen scaling: 'learning/screen-scaling.md'
  - Object animation: 'learning/object-animation.md'
- Building project:
  - Building for Android: 'building-project/building-for-android.md'
  - Building for iOS: 'building-project/building-for-ios.md'
  - Building for HTML5: 'building-project/building-for-html5.md'
